name: Blue Green Deployment

on:
  push:
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Google Authentication
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: jq .version package.json -r

      - name: Build
        run: docker build -t us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr-blue-green:${{ steps.version.outputs.value }} .

      - name: Push
        run: docker push us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr-blue-green:${{ steps.version.outputs.value }}

      - id: deploy
        name: Deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: gcr-blue-green
          image: us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr-blue-green:${{ steps.version.outputs.value }}
          region: us-east4
      
      - name: Healthcheck
        run: curl ${{ steps.deploy.outputs.url }}

