name: Blue Green Deployment

on:
  push:
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Authentication
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: jq .version package.json -r

      - name: Docker build + push
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: gcr.io
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          image_name: us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr-blue-green
          image_tag: ${{ steps.version.outputs.value }}
          dockerfile: ./Dockerfile
          context: .
          
      - id: deploy
        name: Deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: gcr-blue-green
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr-blue-green:${{ steps.version.outputs.value }}
          region: us-central1
      
      - name: Healthcheck
        run: curl ${{ steps.deploy.outputs.url }}